"""Blender integration, properties, runtime cache, and materials."""
from voxel_workspace.blender.properties import (
    VoxelMeshProperties,
    VoxelObjectProperties,
    init_voxel_mesh_properties,
    init_voxel_object_properties,
    get_volume_uuid,
    register_properties,
    unregister_properties,
)
from voxel_workspace.blender.runtime import (
    VoxelVolumeEntry,
    register_volume,
    unregister_volume,
    get_volume,
    has_volume,
    clear_registry,
    all_volumes,
    get_active_volume_uuid,
    set_active_volume_uuid,
    get_active_volume,
    deduplicate_mesh_uuids,
    cleanup_stale_volumes,
    register_runtime,
    unregister_runtime,
)

__all__ = [
    "VoxelMeshProperties",
    "VoxelObjectProperties",
    "init_voxel_mesh_properties",
    "init_voxel_object_properties",
    "get_volume_uuid",
    "register_properties",
    "unregister_properties",
    "VoxelVolumeEntry",
    "register_volume",
    "unregister_volume",
    "get_volume",
    "has_volume",
    "clear_registry",
    "all_volumes",
    "get_active_volume_uuid",
    "set_active_volume_uuid",
    "get_active_volume",
    "deduplicate_mesh_uuids",
    "cleanup_stale_volumes",
    "register_runtime",
    "unregister_runtime",
]
